/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PollOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'district' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'state' : IDL.Text,
  'fatherName' : IDL.Text,
  'village' : IDL.Text,
  'aadharPhoto' : ExternalBlob,
});
export const ChatMessageContent = IDL.Variant({
  'video' : ExternalBlob,
  'text' : IDL.Text,
  'photo' : ExternalBlob,
});
export const UserRegistration = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'district' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'state' : IDL.Text,
  'fatherName' : IDL.Text,
  'village' : IDL.Text,
  'aadharPhoto' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPoll' : IDL.Func([IDL.Text, IDL.Vec(PollOption)], [IDL.Nat], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([], [IDL.Vec(ChatMessageContent)], ['query']),
  'getPollResults' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'question' : IDL.Text,
          'votes' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
          'options' : IDL.Vec(PollOption),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnnouncement' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([UserRegistration], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ChatMessageContent], [], []),
  'voteInPoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PollOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const Announcement = IDL.Record({ 'id' : IDL.Nat, 'message' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'district' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'state' : IDL.Text,
    'fatherName' : IDL.Text,
    'village' : IDL.Text,
    'aadharPhoto' : ExternalBlob,
  });
  const ChatMessageContent = IDL.Variant({
    'video' : ExternalBlob,
    'text' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const UserRegistration = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'district' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'state' : IDL.Text,
    'fatherName' : IDL.Text,
    'village' : IDL.Text,
    'aadharPhoto' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPoll' : IDL.Func([IDL.Text, IDL.Vec(PollOption)], [IDL.Nat], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([], [IDL.Vec(ChatMessageContent)], ['query']),
    'getPollResults' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'question' : IDL.Text,
            'votes' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
            'options' : IDL.Vec(PollOption),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnnouncement' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([UserRegistration], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ChatMessageContent], [], []),
    'voteInPoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };