/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement { 'id' : bigint, 'message' : string }
export type ChatMessageContent = { 'video' : ExternalBlob } |
  { 'text' : string } |
  { 'photo' : ExternalBlob };
export type ExternalBlob = Uint8Array;
export interface PollOption { 'id' : bigint, 'text' : string }
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'mobileNumber' : string,
  'district' : string,
  'whatsappNumber' : string,
  'state' : string,
  'fatherName' : string,
  'village' : string,
  'aadharPhoto' : ExternalBlob,
}
export interface UserRegistration {
  'age' : bigint,
  'name' : string,
  'mobileNumber' : string,
  'district' : string,
  'whatsappNumber' : string,
  'state' : string,
  'fatherName' : string,
  'village' : string,
  'aadharPhoto' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPoll' : ActorMethod<[string, Array<PollOption>], bigint>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChat' : ActorMethod<[], Array<ChatMessageContent>>,
  'getPollResults' : ActorMethod<
    [bigint],
    {
      'question' : string,
      'votes' : Array<[bigint, bigint]>,
      'options' : Array<PollOption>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postAnnouncement' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[UserRegistration], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ChatMessageContent], undefined>,
  'voteInPoll' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];